# Generated by Django 5.1.2 on 2024-10-22 16:37

import core.utils.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('price', models.PositiveIntegerField(validators=[core.utils.validators.validate_positive])),
                ('color', models.CharField(max_length=50)),
                ('screen_size', models.FloatField(validators=[core.utils.validators.validate_positive])),
                ('status', models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='N', max_length=10)),
                ('country_of_manufacture', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.brand')),
            ],
        ),
    ]
